apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: artifactregistry-charts-reader
  namespace: acm-workshop-618-tenant
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/IAMServiceAccount/helm-charts-reader,artifactregistry.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/ArtifactRegistryRepository/charts
spec:
  memberFrom:
    serviceAccountRef:
      name: helm-charts-reader
      namespace: acm-workshop-618-tenant
  resourceRef:
    kind: ArtifactRegistryRepository
    name: charts
  role: roles/artifactregistry.reader
