apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
  name: gke-asm-ingressgateway
  namespace: acm-workshop-618-tenant
spec:
  adaptiveProtectionConfig:
    layer7DdosDefenseConfig:
      enable: true
  advancedOptionsConfig:
    logLevel: VERBOSE
  rule:
  - action: allow
    description: "Default rule"
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - "*"
    priority: 2147483647
  - action: deny(403)
    description: "XSS"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('xss-v33-canary')"
    priority: 1000
  - action: deny(403)
    description: "SQL injection level 2"
    match:
      expr:
        expression: "evaluatePreconfiguredWaf('sqli-v33-canary', {'sensitivity': 2, 'opt_out_rule_ids': ['owasp-crs-v030301-id942200-sqli', 'owasp-crs-v030301-id942260-sqli', 'owasp-crs-v030301-id942430-sqli']})"
    priority: 2000
  - action: deny(403)
    description: "Local file inclusion"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('lfi-v33-canary')"
    priority: 3000
  - action: deny(403)
    description: "Remote file inclusion"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('rfi-v33-canary')"
    priority: 4000
  - action: deny(403)
    description: "CVE-2021-44228 and CVE-2021-45046"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('cve-canary')"
    priority: 12345
  - action: deny(403)
    description: "Remote code execution"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('rce-v33-canary')"
    priority: 5000
  - action: deny(403)
    description: "Method enforcement"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('methodenforcement-v33-canary')"
    priority: 6000
  - action: deny(403)
    description: "Scanner detection"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('scannerdetection-v33-canary')"
    priority: 7000
  - action: deny(403)
    description: "Protocol attack"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('protocolattack-v33-canary')"
    priority: 8000
  - action: deny(403)
    description: "PHP injection attack"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('php-v33-canary')"
    priority: 9000
  - action: deny(403)
    description: "Session fixation attack"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('sessionfixation-v33-canary')"
    priority: 10000
  - action: deny(403)
    description: "Java attack"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('java-v33-canary')"
    priority: 11000
  - action: deny(403)
    description: "NodeJS attack"
    match:
      expr:
        expression: "evaluatePreconfiguredExpr('nodejs-v33-canary')"
    priority: 12000
