apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: gke
  namespace: acm-workshop-618-tenant
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
    config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/ContainerCluster/gke
spec:
  location: global
  authority:
    issuer: https://container.googleapis.com/v1/projects/acm-workshop-618-tenant/locations/northamerica-northeast1/clusters/gke
  endpoint:
    gkeCluster:
      resourceRef:
        name: gke
