apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-acm-membership
  namespace: acm-workshop-618-tenant
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/GKEHubMembership/gke,gkehub.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/GKEHubFeature/configmanagement
spec:
  projectRef:
    external: projects/acm-workshop-618-tenant
  location: global
  membershipRef:
    name: gke
  featureRef:
    name: configmanagement
  configmanagement:
    configSync:
      sourceFormat: unstructured
      preventDrift: true
      git:
        policyDir: .
        secretType: none
        syncBranch: main
        syncRepo: https://github.com/mathieu-benoit/acm-workshop-gke-configs-repo
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
    version: "1.14.1"
