apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-mesh-membership
  namespace: acm-workshop-618-tenant
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/GKEHubMembership/gke,gkehub.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/GKEHubFeature/servicemesh
spec:
  projectRef:
    external: acm-workshop-618-tenant
  location: global
  membershipRef:
    name: gke
  featureRef:
    name: servicemesh
  mesh:
    management: MANAGEMENT_AUTOMATIC
