apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringAlertPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
  name: monitoring-alert-policy-uptime-checks
spec:
  displayName: Failure of uptime checks
  enabled: true
  notificationChannels:
    - name: monitoringnotificationchannel-email
  combiner: OR
  conditions:
  - displayName: Failure of uptime check_id uptime-check-for-google-cloud-site
    conditionThreshold:
      filter: metric.type="monitoring.googleapis.com/uptime_check/check_passed" AND resource.type="uptime_url"
      aggregations:
      - perSeriesAligner: ALIGN_NEXT_OLDER
        alignmentPeriod: 1200s
        crossSeriesReducer: REDUCE_COUNT_FALSE
        groupByFields:
        - resource.label.*
      comparison: COMPARISON_GT
      thresholdValue: 1
      duration: 60s
      trigger:
        count: 1
