apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: monitoring-viewer
  namespace: acm-workshop-618-tenant
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/IAMServiceAccount/gke-primary-pool
spec:
  memberFrom:
    serviceAccountRef:
      name: gke-primary-pool
      namespace: acm-workshop-618-tenant
  resourceRef:
    kind: Project
    external: acm-workshop-618-tenant
  role: roles/monitoring.viewer
