apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
  name: gke-asm-ingressgateway
  namespace: acm-workshop-618-tenant
spec:
  location: global
