apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: gke
  namespace: acm-workshop-618-tenant
  annotations:
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/ComputeNetwork/gke
spec:
  networkRef:
    name: gke
  region: northamerica-northeast1
