apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
  name: gke
  namespace: acm-workshop-618-tenant
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
