apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringUptimeCheckConfig
metadata:
  name: uptimecheckconfig-acm-workshop
spec:
  projectRef:
    name: projects/acm-workshop-618-tenant
  displayName: acm-workshop
  period: 900s
  timeout: 5s
  monitoredResource:
    type: "uptime_url"
    filterLabels:
      host: acm-workshop.alwaysupalwayson.com
      project_id: acm-workshop-618-tenant
  httpCheck:
    port: 443
    requestMethod: GET
    useSsl: true
    validateSsl: true
