apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/ComputeNetwork/gke
  name: cart-tls
  namespace: acm-workshop-618-tenant
spec:
  authorizedNetworkRef:
    name: gke
  memorySizeGb: 1
  redisVersion: REDIS_6_X
  region: northamerica-northeast1
  tier: BASIC
  transitEncryptionMode: SERVER_AUTHENTICATION
