apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: spanner-db-user
  namespace: acm-workshop-618-tenant
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/IAMServiceAccount/spanner-db-user,spanner.cnrm.cloud.google.com/namespaces/acm-workshop-618-tenant/SpannerDatabase/carts
spec:
  memberFrom:
    serviceAccountRef:
      name: spanner-db-user
      namespace: acm-workshop-618-tenant
  resourceRef:
    kind: SpannerDatabase
    name: carts
  role: roles/spanner.databaseUser
