apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
  name: spanner-db-user
  namespace: acm-workshop-618-tenant
spec:
  displayName: spanner-db-user
