apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: acm-workshop-618-tenant
  name: onlineboutique
  namespace: acm-workshop-618-tenant
spec:
  config: regional-northamerica-northeast1
  displayName: onlineboutique
  numNodes: 2
